version: '3'
services:
  reverseproxy:
    hostname: nginx
    container_name: nginx
    image: 086951686584.dkr.ecr.eu-central-1.amazonaws.com/xpov-dev-nginx:latest
    ports:
      - "80:80"
  flask:
    depends_on:
        - reverseproxy
    hostname: flask
    image: 086951686584.dkr.ecr.eu-central-1.amazonaws.com/xpov-dev-falsk-app:latest
    container_name: flask
    restart: always
    links:
      - reverseproxy