version: '3.5'

services:
    reverseproxy:
        image: nginx-revers:latest
        ports:
            - 8080:8080
            
        restart: always
  
    backend:
        depends_on:
            - reverseproxy
        image: xpovi:latest
        restart: always