name: docker build call

on:
  push:
    branches:
      - "dev"
      - "stg"
      - "uat"
      - "main" #prod
    paths-ignore:
      - '01-infra/**'
      - '.github/workflows/terraform_*.yml'

  pull_request:
    branches:
      - "dev"
      - "stg"
      - "uat"
      - "main" #prod
    paths-ignore:
      - '01-infra/**'
      - '.github/workflows/terraform_*.yml'


jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.vars.outputs.branch_name }}
    steps:

      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]
          then
            echo ::set-output name=branch_name::${{ github.event.pull_request.base.ref }}
            echo ${{ github.event.pull_request.base.ref }}
          else
            echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
            echo ${GITHUB_REF#refs/*/}
          fi
          echo "sha_short::${GITHUB_SHA::7}"
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"

  call-build-dev:
    needs: prepare
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/dev') || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev' && github.event.action != 'closed') }}
    uses: ./.github/workflows/build_reuse.yml
    with:
      environment: ${{ needs.prepare.outputs.branch_name }}
      github_event_name: ${{ github.event_name }}
    secrets:
      # GIT_ACTION_PAT: ${{ secrets.GIT_ACTION_PAT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
