
name: Release

on:
  workflow_dispatch:



jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    outputs:
      incremented-release-candidate-version: ${{ steps.increment-release-candidate.outputs.next-version }}
      initial-release-candidate-version: ${{ steps.new-release-candidate-version.outputs.next-version }}
    
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
        
      - name: Get Latest Prerelease Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
          
      - name: Get rc_version From VERSION
        run: echo "RC_VERSION=$(jq -e -r .rc_version VERSION)" >> $GITHUB_OUTPUT
        id: rc_version

      - name: Increment Release Candidate
        if: contains(steps.get-latest-tag.outputs.tag, steps.rc_version.outputs.RC_VERSION) == true
        id: increment-release-candidate
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.get-latest-tag.outputs.tag }}
          version-fragment: rc        
          
      - name: Create New Release Candidate Version
        if: contains(steps.get-latest-tag.outputs.tag, steps.rc_version.outputs.RC_VERSION) == false
        id: new-release-candidate-version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.rc_version.outputs.RC_VERSION }}
          version-fragment: rc

  create-prerelease:
    runs-on:
      - ubuntu-latest
    
    needs:
      - get-change-prerelease-tag
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: PreRelease Incremented Tag
        if: needs.get-change-prerelease-tag.outputs.incremented-release-candidate-version != ''
        id: incremented-release
        uses: igorrs/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.get-change-prerelease-tag.outputs.incremented-release-candidate-version }}
          release_name: ${{ needs.get-change-prerelease-tag.outputs.incremented-release-candidate-version }}
          prerelease: true
          
      - name: PreRelease New Tag
        if: needs.get-change-prerelease-tag.outputs.initial-release-candidate-version != ''
        id: new-release
        uses: igorrs/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.get-change-prerelease-tag.outputs.initial-release-candidate-version }}
          release_name: ${{ needs.get-change-prerelease-tag.outputs.initial-release-candidate-version }}
          prerelease: true