
name: Release

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true


jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2