name: "Snipe-IT CI-CD"
on:
  push:
    branches:
      - dev
      # - stage
      # - main
    paths:
      - '01-infra/**'

defaults:
  run:
    shell: bash
    working-directory: 01-infra/infra

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: aws
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: us-east-1
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}



      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1


      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive -diff

      - name: Terraform Init
        id: init
        run: |
            terraform init \
            -backend-config=../backend/dev.conf

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        # if: github.event_name == 'pull_request'
        run: |
          terraform plan \
          -var="aws-access-key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="aws-secret-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          --var-file="../envs/dev.tfvars"
        # continue-on-error: true

      - name: Terraform deploy
        # if: inputs.github_event_name == 'push'
        run: |
          terraform apply \
          -var="aws-access-key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="aws-secret-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          --var-file="../envs/dev.tfvars"


  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run infracost diff
        uses: infracost/infracost-gh-action@master
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: 01-infra/infra