name: "Snipe-IT CI-CD"
on:
  push:
    branches:
      - dev
      # - stage
      # - main
    paths:
      - '01-infra/**'

defaults:
  run:
    shell: bash
    working-directory: 01-infra/dev

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Terraform Format
      #   id: fmt
      #   run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
            terraform init -var="aws-access-key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws-secret-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -backend-config ../backend/dev.conf -=var-file=../db.tfvars

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true
